#ifndef UART_CONFIG_H
#define UART_CONFIG_H

#define UART_U8_PARITY    UART_PARITY_DISABLED

#define UART_U8_BAUD_RATE UART_BAUD_9600

#define UART_U8_STOP_BITS UART_STOP_1_BIT

#define UART_U8_SYS_FREQ UART_SYS_FREQ_8M

#define UART_U32_TIME_OUT_TH 1000

#endif
